CREATE USER MIGMOR WITH
NOSUPERUSER
PASSWORD 'abreu'
VALID UNTIL '2099-07-04';

CREATE USER ATD WITH
NOSUPERUSER
PASSWORD 'jimenez'
VALID UNTIL '2099-09-25';

CREATE USER DOR WITH
NOSUPERUSER
PASSWORD 'taboloquilla'
VALID UNTIL '2015-10-11';

GRANT SELECT,DELETE
ON juguete,marca
TO MIGMOR
WITH GRANT OPTION;


GRANT SELECT,INSERT
ON empleado,distribuidor
TO ATD
WITH GRANT OPTION;

GRANT DELETE,UPDATE,INSERT
ON direccion_cliente,direccion_sucursal
TO DOR;

REVOKE DELETE,INSERT,UPDATE
ON juguete,marca,empleado,distribuidor,direccion_cliente,direccion_sucursal
FROM MIGMOR,ATD,DOR;

